### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Faederwulf** [quodroc/HumbleNewTabPage#70]
From the Firefox Add-ons page I get: `Download failed. Please check your connection.`
If I download the xpi and try to load it manually, I get: `This add-on could not be installed because it appears to be corrupt`

I'm using IceCat 60.3.0esr (64-bit)

**Comment by johnrorschach** [comment]
Same here
Is there a solution?I really like the add on

**Comment by quodroc** [comment]
No idea what the problem is. I found similar reports here:
https://www.linuxquestions.org/questions/slackware-14/can't-install-extensions-on-icecat-4175646560/
https://aur.archlinux.org/packages/icecat-bin/#comment-673917

The extension appears to work fine via "Load Temporary Add-on" at about:debugging so it must just be a bug in IceCat.

**Comment by quodroc** [comment]
Figured out the problem. IceCat requires an explicity addon ID in the manifest, whereas it is optional in Firefox. I just uploaded a new version that should install correctly: https://addons.mozilla.org/firefox/addon/humble-new-tab/

**Comment by johnrorschach** [comment]
Thank you so much for your fast reply!!works perfectly 15.05.2019, 03:02, "Isaiah Billingsley" <notifications@github.com>:Figured out the problem. IceCat requires an explicity addon ID in the manifest, whereas it is optional in Firefox. I just uploaded a new version that should install correctly: https://addons.mozilla.org/firefox/addon/humble-new-tab/—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
